### ISSUE TITLE
install poop

### ISSUE THREAD

**Issue by staabm** [andrewrk/poop#32]
am I supposed to manually download poop from the releases page?

is there a way I can install poop via e.g. a package manager, so I can easily update it, without re-downloading manually?
any recommended way to install it?

would be great to have a few words about installation in the README

**Comment by xdBronch** [comment]
not much "installing" per se since its just a single file. making it executable and moving into a dir thats in path is all thats needed. i have the source cloned with a symlink in my path so if something changes i just rebuild it

**Comment by andrewrk** [comment]
Installing open source software is essentially the same for every project, and poop is no exception. If it's a new project, such as this one, then you have to build from source, or use the upstream-provided binary distributions. Once a project becomes popular and mature enough, it finds its way into various package managers, which are managed by third parties. Soooo you should go pester Debian, or Homebrew, or whomever runs the package manager that you personally want to use, and file a ticket there to request poop packaging. Good luck!
