### ISSUE TITLE
Build Instructions are poor

### ISSUE THREAD

**Issue by b-kaiser** [andrewrk/poop#34]
1. Some OS'es still ship `zig-0.9.1` including mine, which is not working on my OS.
3. I was not able to find the specified, `tested` zig version here https://ziglang.org/download/.
4. `zig-0.11.0-dev.3786+8dcb4a3dc` (for linux_x86_64 in my case) is working. I couldn't find a different `0.11` version for direct download.
5. Build instructions can be found here `https://ziglang.org/learn/getting-started/#direct-download`, and it is a little awkward to find them, to be honest. On the other hand, one only needs to extract it with `xz --decompress` and add the extracted directory to your path. I suggest to mention this.
6. Users of `poop` that aren't zig devs, likely do not want to set up a nighty build / nighlty download of a prebuild binary, and the version for download likely keeps changing. That is a tough situation, and should be at least mentioned. 
2. I did not check whether some `zig-0.10` is working, but using a more stable version might be more convenient for users of `poop` that aren't zig-devs.

**Comment by andrewrk** [comment]
https://github.com/andrewrk/poop/pull/35#issuecomment-1605791460
